// Board settings for Waveshare RP2350B Plus W.
// Adapted from Waveshare's RP2350B-Plus-W C examples (BSD-3-Clause).
#ifndef _BOARDS_WAVESHARE_RP2350B_PLUS_W
#define _BOARDS_WAVESHARE_RP2350B_PLUS_W

pico_board_cmake_set(PICO_PLATFORM, rp2350)

#define WAVESHARE_RP2350B_PLUS_W
#define PICO_RP2350A 0

#ifndef PICO_DEFAULT_UART
#define PICO_DEFAULT_UART 0
#endif
#ifndef PICO_DEFAULT_UART_TX_PIN
#define PICO_DEFAULT_UART_TX_PIN 0
#endif
#ifndef PICO_DEFAULT_UART_RX_PIN
#define PICO_DEFAULT_UART_RX_PIN 1
#endif

#ifndef PICO_DEFAULT_I2C
#define PICO_DEFAULT_I2C 0
#endif
#ifndef PICO_DEFAULT_I2C_SDA_PIN
#define PICO_DEFAULT_I2C_SDA_PIN 4
#endif
#ifndef PICO_DEFAULT_I2C_SCL_PIN
#define PICO_DEFAULT_I2C_SCL_PIN 5
#endif

#define PICO_BOOT_STAGE2_CHOOSE_W25Q080 1
#ifndef PICO_FLASH_SPI_CLKDIV
#define PICO_FLASH_SPI_CLKDIV 2
#endif
#ifndef PICO_FLASH_SIZE_BYTES
#define PICO_FLASH_SIZE_BYTES (16 * 1024 * 1024)
#endif
#ifndef PICO_RP2350_A2_SUPPORTED
#define PICO_RP2350_A2_SUPPORTED 1
#endif

// Radio pins verified against the Waveshare RP2350B-Plus-W schematic.
pico_board_cmake_set(PICO_CYW43_SUPPORTED, 1)
#define CYW43_WL_GPIO_COUNT 3
#define CYW43_WL_GPIO_LED_PIN 0
#define CYW43_PIN_WL_DYNAMIC 0
#define CYW43_DEFAULT_PIN_WL_REG_ON 36u
#define CYW43_DEFAULT_PIN_WL_DATA_OUT 37u
#define CYW43_DEFAULT_PIN_WL_DATA_IN 37u
#define CYW43_DEFAULT_PIN_WL_HOST_WAKE 37u
#define CYW43_DEFAULT_PIN_WL_CLOCK 39u
#define CYW43_DEFAULT_PIN_WL_CS 38u
#endif
